REWARD_CORRECT_ACTION = 0.2
REWARD_PROGRESS = 0.3
REWARD_MILESTONE = 0.5
REWARD_CONFLICT_RESOLUTION = 0.5
REWARD_FINAL_SUCCESS = 1.0

PENALTY_WRONG_ACTION = -0.2
PENALTY_RULE_VIOLATION = -0.3
PENALTY_REPEATED_ACTION = -0.1
